namespace BlueDotBrigade.Weevil.Data
{
	public static class MetadataType
	{
		/// <summary>
		/// Represents a user's comment.
		/// </summary>
		public static string Comment => "Comment";
		/// <summary>
		/// Represents the amount of time that has elapsed between the current the preceeding record.
		/// </summary>
		public static string ElapsedTime => "ElapsedTime";

		/// <summary>
		/// Indicates that the record should remain visible, regardless of the filter that is being applied.
		/// </summary>
		public static string IsPinned => "IsPinned";

		/// <summary>
		/// Indicates that the record was generated by the application's UI thread.
		/// </summary>
		public static string FromUiThread => "FromUiThread";

		/// <summary>
		/// Indicates that the record includes a newline (<c>\n</c>) and/or and carriage return (<c>\r</c>) character.
		/// </summary>
		public static string IsMultiLine => "IsMultiLine";
	}
}
