namespace BlueDotBrigade.Weevil.Analysis
{
	using System;
	using System.Collections.Immutable;
	using System.Linq;
	using BlueDotBrigade.Weevil.Data;
	using BlueDotBrigade.Weevil.Diagnostics;
	using BlueDotBrigade.Weevil.IO;

	/// <summary>
	/// Analyzes a file looking for time periods where logging appears to have stopped.
	/// </summary>
	public class TimeGapAnalyzer : IRecordAnalyzer
	{
		private static readonly TimeSpan DefaultThreshold = TimeSpan.FromSeconds(60);

		private const int UnknownIndex = -1;

		private readonly bool _uiThreadOnly;
		
		private TimeSpan _maximumPeriodDetected;
		private int _count;
		private DateTime _firstOccurrenceAt;

		public TimeGapAnalyzer(bool uiThreadOnly)
		{
			_uiThreadOnly = uiThreadOnly;
			_maximumPeriodDetected = TimeSpan.Zero;
			_count = -1;
			_firstOccurrenceAt = DateTime.MaxValue;
		}
		public virtual string Key => _uiThreadOnly
			? AnalysisType.TimeGapUiOnly.ToString()
			: AnalysisType.TimeGap.ToString();

		public virtual string DisplayName => _uiThreadOnly
			? "Detect Time Gap (UI Only)"
			: "Detect Time Gap";

		public TimeSpan MaximumPeriodDetected => _maximumPeriodDetected;

		public int Count => _count;

		public DateTime FirstOccurrenceAt => _firstOccurrenceAt;

		public int Analyze(ImmutableArray<IRecord> records, string outputDirectory, IUserDialog userDialog, bool canUpdateMetadata)
		{
			if (TryGetTolerance(userDialog, out TimeSpan maximumAllowedPeriod))
			{
				Analyze(records, maximumAllowedPeriod, canUpdateMetadata);
			}

			return this.Count;
		}

		private static int IndexOfFirstTimestamp(ImmutableArray<IRecord> records, bool uiThreadOnly)
		{
			var result = UnknownIndex;

			for (var i = 0; i < records.Length; i++)
			{
				if (uiThreadOnly)
				{
					if (records[i].HasCreationTime && records[i].Metadata.WasGeneratedByUi)
					{
						result = i;
						break;
					}
				}
				else
				{
					if (records[i].HasCreationTime)
					{
						result = i;
						break;
					}
				}

			}

			return result;
		}

		/// <summary>
		/// Analyzes the <paramref name="records"/> looking for time periods where logging appears to have stopped.
		/// </summary>
		/// <remarks>
		/// The analysis is performed using actual <see cref="Record.CreatedAt"/> timestamps, 
		/// and not the <see cref="Metadata.ElapsedTime"/> value which is generated by the current view.
		/// </remarks>
		public int Analyze(ImmutableArray<IRecord> records, TimeSpan maximumAllowedPeriod, bool canUpdateMetadata)
		{
			Log.Default.Write(LogSeverityType.Debug, "Time gap analysis is starting...");

			_maximumPeriodDetected = TimeSpan.Zero;
			_count = 0;

			var previous = IndexOfFirstTimestamp(records, _uiThreadOnly);

			if (previous == UnknownIndex)
			{
				if (canUpdateMetadata)
				{
					foreach (IRecord record in records)
					{
						record.Metadata.IsFlagged = false;
					}
				}
			}
			else
			{
				for (var current = previous; current < records.Length; current++)
				{
					IRecord currentRecord = records[current];

					if (canUpdateMetadata)
					{
						currentRecord.Metadata.IsFlagged = false;
					}

					if (_uiThreadOnly)
					{
						if (currentRecord.Metadata.WasGeneratedByUi)
						{
							CheckForTimeGap(currentRecord, records[previous], maximumAllowedPeriod, canUpdateMetadata);

							previous = current;
						}
					}
					else
					{
						CheckForTimeGap(currentRecord, records[previous], maximumAllowedPeriod, canUpdateMetadata);

						previous = current;
					}
				}
			}

			LogSeverityType severityType = _count > 0 ? LogSeverityType.Warning : LogSeverityType.Information;
			Log.Default.Write(severityType, $"Time gap analysis is complete. UiThreadOnly={_uiThreadOnly}, ProblemsDetected={_count}, MaximumPeriodDetected={_maximumPeriodDetected}, MaximumAllowedPeriod={maximumAllowedPeriod}");

			return _count;
		}

		protected virtual void CheckForTimeGap(IRecord currentRecord, IRecord previousRecord, TimeSpan maximumAllowedPeriod,
			bool canUpdateMetadata)
		{
			TimeSpan elapsedTime = currentRecord.CreatedAt - previousRecord.CreatedAt;

			_maximumPeriodDetected = elapsedTime > _maximumPeriodDetected
				? elapsedTime
				: _maximumPeriodDetected;

			if (elapsedTime > maximumAllowedPeriod)
			{
				_count++;

				if (_count == 1)
				{
					_firstOccurrenceAt = currentRecord.CreatedAt;
				}

				if (canUpdateMetadata)
				{
					currentRecord.Metadata.IsFlagged = true;

					var commentLabel = _uiThreadOnly ? "UiTimeGap" : "TimeGap";

					currentRecord.Metadata.UpdateUserComment(
						$"{commentLabel}: {TimeSpanExtensions.ToHumanReadable(elapsedTime)}");
				}
			}
		}

		protected virtual bool TryGetTolerance(IUserDialog user, out TimeSpan unresponsivenessPeriod)
		{
			var userInput = user.ShowUserPrompt(
				"Input Required",
				"Maximum delay (ms):",
				DefaultThreshold.TotalMilliseconds.ToString("0.#"));

			var wasSuccessful = int.TryParse(userInput, out var timePeriodInMs);

			unresponsivenessPeriod = wasSuccessful ? TimeSpan.FromMilliseconds(timePeriodInMs) : TimeSpan.Zero;

			return wasSuccessful;
		}
	}
}
